### ISSUE TITLE
Setting from multi-line ENV value

### ISSUE THREAD

**Issue by v-kolesnikov** [dry-rb/dry-system#102]
Dry-System `settings` component can't fetch multi-line value from .env file.

Gem `dotenv` supports it: https://github.com/bkeepers/dotenv#multi-line-values, so we can implement the same functionality.

I even think further - plugins (such `settings`) should be more external and maybe are not a part of the core of dry-system because it much harder to support stable core and plugins in the same time.

**Comment by timriley** [comment]
Since we now use dotenv in #204, this should be fixed.
