### ISSUE TITLE
Attempt to lazy-load components when non-finalized container is asked for `key?`

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#109]
We should copy the behaviour of `#resolve` on a non-finalized container:

```
        # @api public
        def resolve(key)
          load_component(key) unless finalized?

          super
        end
```

And do the same for `key?`. This would help unit testing of `Dry::Transaction` objects (i.e. alongside a non-finalized container), which [check with the container for a `key?` before attempting to resolve an object from it](https://github.com/dry-rb/dry-transaction/blob/08617f7f564f4871670600665b225bdf8cd1be9d/lib/dry/transaction/operation_resolver.rb#L9-L10).

**Comment by flash-gordon** [comment]
resolved by #120
