### ISSUE TITLE
Using bare `register` with block arg inside bootable component (e.g. with `namespace: true`) does not result in a block-style registration on the top-level container

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#124]
e.g.

```ruby
MyApp::Container.boot :models, namespace: true do |system|
  start do
    register "foo" do
      puts "Resolving foo!"
      Object.new
    end
  end
end
```

When the container boots, this will print "Resolving foo!" exactly 1 time, and every resolution of `"models.foo"` afterwards will return the _exact same object_.

It appears that the magical merging of this DSL-specific container into the top-level container throws away our intention here, which is for the block to run every time the object is resolved.

**Comment by solnic** [comment]
You can probably workaround that via `system.register`.

**Comment by timriley** [comment]
Yep, that’s what I did. 

We should still fix this though, it’s a trap for new players.
