### ISSUE TITLE
Cannot use logging plugin's logger component in a dependency boot file

### ISSUE THREAD

**Issue by jezstephens** [dry-rb/dry-system#146]
**Describe the bug**

I am not able to access the logger provided by the `logging` plugin from a dependency boot file. It seems that bootable dependencies are only able to use other bootable dependencies, perhaps?

**To Reproduce**

Use the logging plugin:
```ruby
# system/container.rb

class Application < Dry::System::Container
  use :logging

  # ...
end
```

And try to use it within a bootable dependency's `start` block [as explained in the docs](https://dry-rb.org/gems/dry-system/0.17/booting/#using-other-bootable-dependencies).
```ruby
# system/boot/db.rb

Application.boot(:db) do |app|
  start do
    use :logger

    register(DB.new(ENV['DB_URL'], logger: app[:logger]))
  end
end
```

**Expected behavior**

The above code works -- the logger can be used from the boot file and provided to the bootable dependency.

**Actual behaviour**

The system fails to boot, with the following error message:

```
Dry::System::InvalidComponentIdentifierError: component identifier +logger+ is invalid or boot file is missing
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter/component_registry.rb:30:in `[]'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:142:in `with_component'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:95:in `start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/container.rb:351:in `start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:91:in `block in use'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:90:in `each'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:90:in `use'
  /app/system/boot/db.rb:3:in `block (2 levels) in <top (required)>'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:115:in `trigger!'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:80:in `start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:52:in `block in call'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:50:in `each'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/lifecycle.rb:50:in `call'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/components/bootable.rb:99:in `start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:99:in `block (2 levels) in start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:86:in `block (2 levels) in init'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:125:in `block in call'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:149:in `with_component'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:122:in `call'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:84:in `block in init'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:149:in `with_component'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:83:in `init'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:98:in `block in start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:149:in `with_component'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:95:in `start'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:66:in `block in finalize!'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter/component_registry.rb:16:in `each'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter/component_registry.rb:16:in `each'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/booter.rb:65:in `finalize!'
  /usr/local/bundle/gems/dry-system-0.17.0/lib/dry/system/container.rb:328:in `finalize!'
```

**Your environment**

- Affects my production application: No
- Ruby version: 2.7.1
- OS: macOS Catalina

**Comment by solnic** [comment]
This is actually expected as `use :foo` will try to start a bootable dependency identified as `:foo`. Logger is registered as a normal component in the [after(:configure)](https://github.com/dry-rb/dry-system/blob/d9b309229d77e2ad691be99c68dbff102fbfcda4/lib/dry/system/plugins/logging.rb#L24) hook so all you need to do is to add `use :logging` *before* you call configure in your container class. Then it'll be available in your boot file.

I'll clarify this in the docs before closing this issue.

**Comment by jezstephens** [comment]
Ah, you're right - I didn't expect it to be that easy! I'm slightly surprised that it is accessible directly as `logger` as well as via `app[:logger]`. The latter form seems slightly preferable to me in the absence of any explicit `use :logger` or `Import[:logger]` or similar.

Thanks for your help and all the work you're putting into the dry libraries!

**Comment by solnic** [comment]
> Ah, you're right - I didn't expect it to be that easy! I'm slightly surprised that it is accessible directly as logger as well as via app[:logger].

Yes, unfortunatelly I thought it's gonna be cool to just expose things via [method_missing](https://github.com/dry-rb/dry-system/blob/d9b309229d77e2ad691be99c68dbff102fbfcda4/lib/dry/system/lifecycle.rb#L123-L126) which now I regret and it'll most likely go away in 1.0.0.

> The latter form seems slightly preferable to me in the absence of any explicit use :logger or Import[:logger] or similar.

I 100% agree 😄

**Comment by timriley** [comment]
Closing this issue now since it was resolved at the time (back in 2020!), and I've now just removed a potential source of confusion (the multiple `use` methods) in #211.
