### ISSUE TITLE
Can not set a false boolean value in settings 

### ISSUE THREAD

**Issue by alexandrubeu** [dry-rb/dry-system#148]
When setting a boolean value to false in settings area
![image](https://user-images.githubusercontent.com/11049718/86783455-fc491080-c068-11ea-8e1b-96422596a35b.png)
That setting should be set to false. 
![image](https://user-images.githubusercontent.com/11049718/86783655-49c57d80-c069-11ea-94c7-f932006acf75.png)

It seems that the current setting can not be set as false, instead I get an error. 
![image](https://user-images.githubusercontent.com/11049718/86783951-9c9f3500-c069-11ea-9aaa-9d62da1612d0.png)

Just set a setting as boolean with the value false. 

Also found the problem:
![image](https://user-images.githubusercontent.com/11049718/86784131-d2dcb480-c069-11ea-9d8e-8180d0dca7a9.png)

It seems that value false is considered as a non-value and it is assigned with `Undefined` 
https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/settings.rb

Provide detailed steps to reproduce, an executable script would be best.

I would expect that the current setting should set as false and not throw errors.

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.4.2
- OS: Ubuntu 20.04

**Comment by solnic** [comment]
Thanks for the report, this is clearly a bug.

**Comment by timriley** [comment]
Out of interest, @alexandrubeu, could you please `p ENV` above that `value = ENV.fetch(...)` line and paste it here? (Being sure to remove any sensitive data you might have).

Thanks!

**Comment by timriley** [comment]
I think this should actually work if you use `Types::Params::Bool` (given that the bool setting will be coming in from the ENV directly, or the ENV as populated by `.env*` files, and will therefore be a string representation of a truthy/falsey values).

At least at this point (January 2022, and at least for recent times as well), we do not offer first-party support for loading settings from YAML files, so I reckon the above should be enough.

I'm closing this issue now given it's stale, but @alexandrubeu if this is still a problem for you, please let us know! 😄
