### ISSUE TITLE
Support `memoize` option on `Container#register`

### ISSUE THREAD

**Issue by ianks** [dry-rb/dry-system#156]
After dropping some some investigation, it looks like the dry-system container does not support the memoize option like a Dry::Container does. This would be really nice for us, because we would like to be able to memoize some things in production. Here’s an example of what it would look like:

```ruby
Container.boot(:ssr_renderer) do
  start do
    register(:ssr_renderer, memoize: false) do
      React::SSR::Renderer.new
    end
  end
end
```

In fact, I wonder if dry-system could just use dry-container here. Thoughts?

**Comment by solnic** [comment]
Looks like it's probably because [here](https://github.com/dry-rb/dry-system/blob/577bca6baaf2e18255eb30c7b9026ef671a209dc/lib/dry/system/components/bootable.rb#L192) it registers items and the memoization option is lost there. I need to debug it though 🙂
