### ISSUE TITLE
Disallow direct access to `config` until `configure` has been run

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#159]
Running `Dry::System::Container.configure`, passing a block, and configuring the container on the yielded object is the recommended way to configure a dry-system container, because we run certain hooks after `.configure` is run for the first time (such as adding configured component_dirs to Ruby's `$LOAD_PATH`).

It's also possible to configure a container by assigning values on it's `.config` directly. This is just how dry-configurable works. Doing this within the context of `Dry::System::Container`, however, may lead to surprising behavior, since it can't provide an opportunity for the after-configure hooks to run.

To improve this situation, we should either:

- Raise an error if `config` is access directly without `configure` having been run first
- Find some other ergonomic way for the user to signal that the after-configuration hooks should run

The former is much simpler than the latter.

**Comment by solnic** [comment]
I believe we want option nr 1 :)

**Comment by timriley** [comment]
I've reflected on this now, and I think it would be undesirable for us to forbid direct access to `config` at any time. This is how dry-configurable is _intended_ to work, and it seems non-ergonomic to do anything else.

Instead, I'm working to expand the API around the overall configuration _phase_ for `Dry::System::Container`. Work in progress is at #207.
