### ISSUE TITLE
Add a `use :zeitwerk` plugin

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#170]
I'd like to make zeitwerk + dry-system work together with a single line, so it should be possible to just throw this into your `Dry::System::Container` subclass:

```ruby
use :zeitwerk
```

This should do the necessary dry-system configuration:

```ruby
config.component_dirs.loader = Dry::System::Loader::Autoloading
config.component_dirs.add_to_load_path = false
```

And it could also perhaps require zeitwerk, set up the base zeitwerk loader, make it available on the container for further manual configuration, if required, and then `setup` the loader as part of the container boot lifecycle.

**Comment by ianks** [comment]
I've got a WIP for this
