### ISSUE TITLE
Add more useful namespace-aware predicate methods to `Dry::System::Identifier`

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#171]
Right now we have just `#start_with?`, but it would be good to have at least `#include?` too, and perhaps some others may also make sense.

**Comment by wuarmin** [comment]
I think `#include?` is a must-have, because it's common (at least for me) to have situations like this:

```ruby
# lib/administration/entities
Administration::Entities::User
# lib/specific_app/entities
SpecificApp::Entities::User
```
In such cases you want to do something like this:
```ruby
    # ...
    config.component_dirs.add "lib" do |dir|
      dir.auto_register = proc do |component|
        !component.identifier.include?('entities')
      end
    end
    # ...
```

**Comment by flash-gordon** [comment]
`.match?` probably

**Comment by solnic** [comment]
Yeah I used both include and match checks so far. start/end_with would be useful too.
