### ISSUE TITLE
Consider bringing back a simpler `instance` callable config for component_dirs

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#180]
To allow users to do what used to be possible like this:

```ruby
auto_register!('services/wallets') do |config|
  config.instance do |component|
    if component.identifier.match?(/workers\./)
      component.loader.constant  # register job classes
    else
      component.instance # register rest components as instances
    end
  end
end
```

Which right now requires subclassing Loader:

```ruby
class AppLoader < Dry::System::Loader
  def self.call(component, *args)
    if component.identifier.match?(/workers\./)
      require!(component)
      constant(component)
    else
      super
    end
  end
end

# in Dry::System::Container config
config.component_dirs.loader = AppLoader
```

Which is a smidge less nice.

We already support "callable" options for `auto_register` and `memoize`, which are passed the `component` object, so a similar `instance` option _might_ be possible, but we'd need to make sure it either suitably _replaces_ the loader (and feels just as helpful) or gracefully augments it.

**Comment by smaximov** [comment]
> but we'd need to make sure it either suitably replaces the loader (and feels just as helpful) or **gracefully augments it**.

I've been thinking about making `loader` accept "callable" option too, e.g.:

```rb
class ConstantLoader < Dry::System::Loader
  def self.call(component, *args)
    require!(component)
    constant(component)
  end
end

# ...
config.component_dirs.add 'services/wallets' do |dir|
  dir.loader = lambda { |component|
    if component.identifier.match?(/workers\./)
      ConstantLoader
    else
      Dry::System::Loader
    end
  }
end
```

I'm not sure if this would play nicely with the global loader config though and [the new autoloader](https://github.com/dry-rb/dry-system/blob/2fab5f0a4d7acdea7e0171b02fa1c63b956280ae/lib/dry/system/loader/autoloading.rb).

**Comment by solnic** [comment]
Loader can also be used to require a component's file so this can't be a simple callable object. I think restoring original `instance` option that can be set to a callable should suffice.
