### ISSUE TITLE
uninitialized constant Dry::System::Plugins (NameError)

### ISSUE THREAD

**Issue by ricardopacheco** [dry-rb/dry-system#262]
## Describe the bug

Cannot start application

## To Reproduce

Just start any application

## My environment

- Affects my production application: **YES**
- Ruby version: 3.1.2
- OS: Windows 11 WSL2 ubuntu 22.04.1 LTS

## Screenshots

![ss1](https://user-images.githubusercontent.com/499567/202903742-46f22f2b-6380-4c23-a9df-e8d006548f8f.png)
![ss2](https://user-images.githubusercontent.com/499567/202903833-a784b175-2b99-46c1-a190-c3a4090147ef.png)
![ss3](https://user-images.githubusercontent.com/499567/202903836-2ffca193-a873-40fd-9e70-d79625a6228c.png)

**Comment by solnic** [comment]
dry-system uses Zeitwerk to load itself now, please just use `require "dry/system"`. There's no more need for any additional requires from `dry/system/*`.
