### ISSUE TITLE
Enable_stub raise can't modify frozen class error

### ISSUE THREAD

**Issue by Tyflomate** [dry-rb/dry-system#265]
Hello!

I'm having a problem in my application which is when I run enable_stubs! in my spec_helper. I first did a new topic on the forum thinking is was my config somehow: https://discourse.dry-rb.org/t/enable-stub-raise-cant-modify-frozen-class-error/1632/1, but now I have a coworker who have the bug aswell as mentionned in comments so i think it might be a bug afterall.

Hope you can help! :pray:

**Comment by timriley** [comment]
Could you please create a reproduction, or a series of reproduction steps?

**Comment by Tyflomate** [comment]
Unfortunately I do not seem to be able to reproduce with an app from scratch ... I'm on Ubuntu 22.04 on a MacBookPro16,1. My coworker also have MacbookPro15,1 but on macOs. On my ubuntu 22.04 on a razer blade stealth it works correctly. Here is my gemfile.lock if it can help: https://paste.bingner.com/paste/b2sh9. Here is our ruby versions:
```bash
MacBookPro16,1: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
MacBookPro15,1: ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin19]
```
Tell me if I can give you other informations that will help

**Comment by solnic** [comment]
This is not a bug, it's an issue with your setup. There's something that gets loaded that freezes the container, most likely through finalization, and then something else that loads the file where you enable stubs. File loading order can differ depending on the machine/OS so, yeah. Please debug this closely on your side, look for the place where you finalize your container and ensure that it does not get finalized in test env.

**Comment by Tyflomate** [comment]
That's the thing, i do not finalize my container anywhere. The only things I do with my container is getting what's been registered inside so I'm a little confused how my container is being frozen. Is there anything from dry that might froze the container ?
It seems to be the initializer `run_prepare_callbacks` in `Rails::Application::Finisher` that freezes my container, before it runs I have an uninitialized constant error when i try to call `finalized?` on my container and after it returns true

**Comment by Tyflomate** [comment]
This is what is called and finalize my container: Dry::Rails::Railtie:15 but i don't know why it's called. Do you have a tip to find how it's called ? Thanks a lot !

**Comment by solnic** [comment]
@Tyflomate if you use the railtie, then it does finalize the container [right here](https://github.com/dry-rb/dry-rails/blob/main/lib/dry/rails/railtie.rb#L64) but freezing happens only if it's not the test env. So I recommend double checking what happens there.

**Comment by Tyflomate** [comment]
Thanks for the tip ! My problem was in my .envrc, for some reason I put `RAILS_ENV=development` that's why my container got frozen in my test... Thanks a lot for helpinig me debugging this !

**Comment by solnic** [comment]
Cool, I'm glad you figured it out 🙂
