### ISSUE TITLE
Manually registered container items aren't lazily loaded

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#33]
We need a convention (FS location and files named based on namespace?) to pick up "manual registration" files and require them if we can't otherwise find a component when trying to lazy load it.

**Comment by timriley** [comment]
So actually, this is an issue that spans a number of things.

One of the issues is how dry-validation allows you to pass default options to your schemas:

```ruby
MyForm = Dry::Validation.Schema do
  configure do
    option :foo, Container["bar.baz"]
  end
end
``` 

With this arrangement, `Container.[]` is used to find the item, rather than the container's injector, and `.[]` doesn't do any kind of lazy component loading at all.

**Comment by timriley** [comment]
In fact, I wonder if we could move the lazy loading behavior out from he injector and into the container resolver itself? i.e., enabling it to work when using `System::Container.[]`

**Comment by AMHOL** [comment]
@timriley I was thinking about this recently and came to the same conclusion, I think a custom resolver would be a good suit for this

**Comment by timriley** [comment]
Cool. Yeah, I reckon we could just transplant whatever is inside the `Injector` class and move it into a resolver.

Then later on we can think about extra logic to support a conventional place for manually registered items, etc.

**Comment by solnic** [comment]
This sounds like a good plan :)

**Comment by davidpelaez** [comment]
Is this why stubbing doesn't work after booting a dependency? I'm not sure. If I stub a manually registered item after booting the dependency that uses it the behavior doesn't change. e.g.

```ruby
      Application.boot :operations # resources.find_transaction is registered here manually as a proc
      Application.stub 'resources.find_transaction', -> *x {
        raise "y" # Never called
      }
```

If I stub and the boot it'll raise as expected. Am I correct in that this is the source of the issue? The best solution in the meantime would be to use auto registration?

**Comment by solnic** [comment]
Uhm, you know you can do `option :foo, -> { App['foo'] }` right? :)

**Comment by solnic** [comment]
> @davidpelaez Is this why stubbing doesn't work after booting a dependency?

That's unrelated, please report an issue if you have trouble stubbing a dep that was registered through booting, just remember that if you finalized a container stubbing won't work at all at the moment as we freeze the container unconditionally (I mentioned in another issue that this can be easily solved by skipping `freeze`-ing when we're in a test mode).

**Comment by timriley** [comment]
Back to the original topic here: with #39 nearly ready to go, I propose that we add a "registrations_dir" setting to `Dry::System::Container` where it can look for files full of manual registrations. It can look there if no loaded component exists and a matching source file can't otherwise be found. It'd probably need to recurse back a little to check for a manual registration file for each part of the component path (i.e. we commonly have a `persistence.rb` manual registration file that registers components in the `"persistence.commands.*" namespace).

Does this seem fair to you? If so, I'll give it a go sometime this week.

**Comment by solnic** [comment]
Makes sense
