### ISSUE TITLE
Auto register and already required files

### ISSUE THREAD

**Issue by vladra** [dry-rb/dry-system#34]
Hi all :v:

We've encountered some unexpected behaviour with auto register.

Let's say I have `Services` folder with 2 files:

```ruby
# 1.rb
class One
end
```

```ruby
# 2.rb
require './1.rb'
class Two
end
```

Both files are inside of some auto register folder. And in this case load order matters, cause if `2.rb` is auto registered (and so required) first, `1.rb` will not be registered at all because [`Kernel.require(component.path)`](https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/container.rb#L454) will return false. Preventing [this code](https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/auto_registrar.rb#L29) from registering component.

So, maybe `Kernel.require(component.path) && yield` should be replaced with:

```ruby
Kernel.require(component.path)
yield
```

Otherwise why it is done with `&&`?

Thanks for help

**Comment by solnic** [comment]
Hey :) What's the reason for requiring '1.rb' manually?

**Comment by vladra** [comment]
Hey ;)

Actually you are right, I just missed this point. Thanks (code with explicit require looks more clear to me though)

But theoretically you could use some dependency because you care about load order, right? And that's why I was thinking why require must return true in the above case. It's skipping component registration anyway if component is already registered.

**Comment by blelump** [comment]
I'd like to add my 5 cents into this topic :smile: . In particular, what if you modeled your object hierarchy and instead of composition, it uses inheritance? It is now impossible to load such structure, because once you've `require`d in subclass, the base class will never get loaded.

I think I get the current intention, I mean to prefer to use composition, but there might be cases to use inheritance as well...

**Comment by solnic** [comment]
Sure, we're not against inheritance, FWIW I use it a lot with dry-struct where it's very helpful in reducing code duplication. We should make it work with dry-system of course. I already mentioned in another issue that it's fine to make that change where we always yield component (assuming it's the bit which gives you trouble).

**Comment by blelump** [comment]
@solnic , sure! Thanks for answering here as well .
