### ISSUE TITLE
[discussion] Find a way to have component registered even though it was previously required

### ISSUE THREAD

**Issue by blelump** [dry-rb/dry-system#35]
Hi!

I've recently entered an issue of which it seems some changes need to be applied [here][1] in order to get it to work. I mean the possiblity to register component even though it was required somewhere else. Consider inheritance as an example – either base class has to be registered first so the order of registering components _must be_ explicit or an extra `require` statement is needed in the subclass so the parent constant is known. Although `Kernel.require(component.path) && yield` is very clever I suppose it may be inconsistent due to the [guard][2] statement present at the method beggining – in essence, if the component exists, go away. Actually the block shouldn't ever be performed if key associated to given component already exists. However, I may not be familiar with all of the use cases, but simple change `Kernel.require(component.path); yield` vastly changes the whole registration process.

From what I've found, the `yield` concerns only use cases when component has to be registered, e.g. [here][3] and [here][4], however in this case [guard][3] forbids registration if a component already exists so we're covered, or at least that's my way of thinking.

The current container apporach prefers aggregation, whereas in certain cases inheritance might be a solution as well. 

What do you guys think about it ?

ps. I ran `Kernel.require(component.path); yield` in my local environment and didn't get into any troubles. The `dry-system` specs have passed as well.

[1]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L454
[2]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L448
[3]: https://github.com/dry-rb/dry-system/blob/34de07d1ad5f7d0344b9610877334eca74cd70ff/lib/dry/system/container.rb#L481
[4]: https://github.com/dry-rb/dry-system/blob/902c0f3c4f6313502ba0f50e68fec51066b33943/lib/dry/system/auto_registrar.rb#L31

**Comment by timriley** [comment]
Yeah, I think we could probably `yield` in all circumstances here. The guard class at the top of `.require_component` will prevent multiple container-level requires anyway, and since a dry-system doesn't necessarily "own" the full load process of whatever Ruby app it lives within, it could very well be the case that some of the files for its components have already been required for some reason.

@blelump – could you please submit a PR with this change?

**Comment by solnic** [comment]
I'm OK with that change, IIRC we don't rely on the fact it yields only when a file was required for the first time in any way.
