### ISSUE TITLE
default_namespace doesn't support multilevel directories.

### ISSUE THREAD

**Issue by dvallance** [dry-rb/dry-system#40]
See: https://discuss.dry-rb.org/t/question-about-dry-system-and-auto-register/160/2

"...I tried using a path separator in the name_space to follow it through. Looks like it can only work with a single name, as the components path gets separated into an array and then the array rejects anything matching the namespace."

**Comment by GustavoCaso** [comment]
I will have a look at this one if no one is already working on it 😄

**Comment by solnic** [comment]
@GustavoCaso great :)
