### ISSUE TITLE
Why are duplicate keys disallowed?

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#41]
@solnic just wondering what your rationale was for this behavior?

```ruby
    it 'raises when identifier/path has duplicated keys' do
      expect { Dry::System::Component.new('foo.bar.foo', namespace: 'foo') }
        .to raise_error(Dry::System::InvalidComponentError, /foo\.bar\.foo/)
    end
```

I came across this today when I had what felt like a reasonable component within one of my systems: `BulkData::Parsers::BulkData`. I've renamed it to work around the issue but it'd be good to understand what the rationale/technical limitation is here. Whatever we end up doing, we could document the outcome :)

**Comment by solnic** [comment]
Because the namespace is the same as the first part of the identifier, which is redundant, and would result in `foo.foo.bar.foo`

**Comment by solnic** [comment]
Closing in favor of an actionable issue #50
