### ISSUE TITLE
Turn `Import` into a code-loader

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-system#43]
Right now we rely on `require` to load files, this is honestly good-enough for me, but I know people are complaining about deeply nested dir structures ie `apps/admin/lib/admin` which just looks odd to somebody who's not used to relying on `require` + LOAD_PATHs. Another issue is that you don't have app's namespace available so each file must define it, which means nesting instead of `class Admin::Something`.

To improve this, it seems like using import modules to require files and set up namespaces would be a good idea. I *think* something like this should be possible:

``` ruby
# apps/admin/system/import.rb
require_relative 'container'

module Admin
  Import = Container.injector do |c|
    c.auto_require = true
    c.auto_namespace = true
  end
end
```

Then, you can have this:

``` ruby
# apps/admin/lib/products/operations/create.rb
require 'admin/import'

# namespaces are created on-the-fly so they are already available
class Admin::Products::Operations::Create
  # this will be translated to:
  #   require "#{Container.root}/lib/product_repo"
  include Admin::Import["product_repo"]  
end
```

Auto-namespaces might be a little too much though, as scanning dirs and defining constants can slow things down, so it's something to experiment with. Auto-requires should be very simple to do though, and it will simplify dir structure so that's gonna be a win for many folks.

WDYT @timriley?

**Comment by timriley** [comment]
I like it, @solnic. You're right, it's one hurdle for many people.

I think it'd be good if we can somehow enable the loader to work for non-injected dependencies too. This would let us unify the code within an app, otherwise we may end up with directly-instantiated objects having to live on different directory paths.

```ruby
require "admin/loader"

# translated to "#{Container.root}/lib/decorators/my_thing"
Admin::Loader.require "decorators/my_thing"

Admin::Products::Operations::Create
  # Maybe we could hang the injector off the loader like so
  include Admin::Loader.import["product_repo"]  

  def call
    # do stuff
    # can do Admin::Decorators::MyThing.new here too, since the file's been loaded
  end
end
```

Reckon something like this might be worth it?

**Comment by solnic** [comment]
Yes, it seems to be a good idea to separate code loader from import module, and have the import use the loader internally, but you can always just use the loader directly

**Comment by GustavoCaso** [comment]
I will have a look at this one

**Comment by GustavoCaso** [comment]
@timriley @solnic I like the idea of having `require` and `import` separate.

I do not see a big problem in implementing something on the lines `Admin::Loader.require "decorators/my_thing"` been a quick win for everyone.

> namespaces are created on-the-fly so they are already available 

To me is quite magical

**Comment by GustavoCaso** [comment]
@solnic @timriley I would like to help with this issue. If you think is a good idea I can start with the `require` part

**Comment by solnic** [comment]
I talked to @timriley today about this feature and we actually decided to hold off for now. It makes more sense to focus on making what we have already (and it's quite a lot) more robust, than to add more features (and this one would be complex). We can revisit this after 1.0.0 is released. Sounds good?

**Comment by GustavoCaso** [comment]
@solnic of course. Sounds great. Is there any special part that we want to strength after the new release?

**Comment by AMHOL** [comment]
@solnic @timriley @GustavoCaso @flash-gordon What do you guys think about making it so that you can pass a hash to `auto_register`? i.e.

```ruby
# apps/main/system/my_app/main/container.rb
module MyApp
  module Main
    class Container < Dry::Web::Container
      require root.join("system/my_app/container")
      import core: MyApp::Container

      configure do |config|
        config.root = Pathname(__FILE__).join("../../..").realpath.dirname.freeze
        config.logger = MyApp::Container[:logger]
        config.default_namespace = "my_app.main"
        # THIS LINE \/\/\/
        config.auto_register = {
          'my_app.main' => 'lib',
          'my_app.main.actions' => 'web/actions'
        }
        # THIS LINE /\/\/\
      end
    end
  end
end

# apps/main/lib/web/action.rb
# auto_register: false

require "slim"
require "my_app/action"
require "my_app/main/container"

module MyApp
  module Main
    module Web
      class Action < MyApp::Action
        configure do |config|
          config.paths = [
            Container.root.join("web/templates")
          ]
          config.context = Container["web.context"]
          config.layout = "application"
        end
      end
    end
  end
end

# apps/main/web/actions/homepage.rb
require "web/action" # lib/web/action.rb => MyApp::Main::Web::Action

module MyApp
  module Main
    module Actions
      class Homepage < MyApp::Main::Web::Action
        configure do |config|
          config.template = "homepage"
        end
      end
    end
  end
end
```

**Comment by timriley** [comment]
@solnic Given our recent autoloader support and the work going on in #197 to give us drop-in Zeitwerk integration, I reckon we can close this. What do you think?

**Comment by timriley** [comment]
@solnic We've come a long way!
