### ISSUE TITLE
Example apps

### ISSUE THREAD

**Issue by JonasFromell** [dry-rb/dry-system#5]
Been trying to implement this in a rack app running Grape::API without much luck. Been copying the structure of the rodakase and lotuskase examples, but getting a bunch of errors. Maybe because the usage guide on this page suggests another folder structure than what is used in those examples (f.e the container is defined in a subdirectory other than boot in rodakase but not on this page).
Are there any plans for an example app that is using dry-component instead of Rodakase::Container?

**Comment by solnic** [comment]
What kind of errors? We're not tied to any framework so things just work. I'm pretty sure it could be used to set up a stack using rack/grape just like I set it up with roda and lotus, err, hanami :)

**Comment by JonasFromell** [comment]
You can check how my app is set up here [https://github.com/octagonstudios/swedimport-api/tree/develop](url). Basically i can't access ROM in my Grape API, it just returns null. I also tried to set up a logger like you have done in rodakase but then it complained about a missing require file.

**Comment by solnic** [comment]
@JonasFromell thanks, I'll try to check it out next week :)

**Comment by JonasFromell** [comment]
Had a small breakthrough today. If i create a subclass inside the GrapeAPI and import my components there then reference an instance of that inside GrapeAPI's helpers method it works just fine. So must be something with how GrapeAPI is instanced (no ruby wizard here, just guessing).

**Comment by davidpelaez** [comment]
I'm facing a similar problem. I don't understand how to use the boot methods. I always get something like `/dry/component/container.rb:113:in `require': cannot load such file -- app/core/boot/ctn.rb`

**Comment by solnic** [comment]
hey guys, sorry I've been slow with dry-component feedback. I'm wrapping up new releases of validation and types gems, and after that I'll be back working on dry-component and rodakase, so I'll look into your issues. I extracted dry-component from rodakase literally during one evening, then I was like "why not releasing it already" :) This stuff definitely needs some polishing to make it work in various contexts. FWIW it's been very solid for us when using in rodakase, despite its immaturity. It's gonna receive a lot of <3 very soon though :) Stay tuned!

**Comment by davidpelaez** [comment]
No pressure. Thanks for all the work! Totally understand, it's quite a bit of things you are working on. Feel free to put any updates here when you get some time. In the meantime I'll keep exploring the amazing dry-* world ;)

**Comment by swistaczek** [comment]
Hey @solnic, I also would appreciate your feedback on that case ;).

**Comment by solnic** [comment]
What kind of feedback are you looking for?

**Comment by solnic** [comment]
Closing due to inactvity
