### ISSUE TITLE
Use dry-inflector (instead of inflecto)

### ISSUE THREAD

**Issue by chastell** [dry-rb/dry-system#63]
dry-system uses the inflecto gem for inferring the class names from file names; according to [this thread](https://discourse.dry-rb.org/t/dry-system-auto-registering-properly-cased-class-names/374) dry-inflector would be a better choice.

**Comment by brolycjw** [comment]
You may wish to try this work-around until they fix this issue:

~~~
class Container < Dry::System::Container
  configure do |config|
    config.root = Engine.root
    config.loader = Class.new(Dry::System::Loader) do
      def constant
        path.camelize.constantize
      end
    end
    config.auto_register = 'lib'
  end
  load_paths!('lib')
end
~~~
