### ISSUE TITLE
Rename Container.require to something else

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#64]
`Container.require` having the same name as `Kernel.require` means awkwardness requiring from the load path inside bootable components, e.g.

```ruby
MyApp::Container.boot :settings, from: :system do
  before(:init) do
    # TODO: we need to rename `Container.require` to something else
    ::Kernel.require "types"
  end

  settings do
    # Declare settings here using `Types` module (required above)
  end
end
```

Having to do `::Kernel.require` inside the bootable component DSL is surprising and will likely cause people issues. And in general, `require` is so widely used in Ruby that we shouldn't try and offer some specialised behaviour behind the same name.

**Comment by solnic** [comment]
Right, this was a major mistake that I've made. Suggestions for a better name?

**Comment by AMHOL** [comment]
Could yield the container to the block rather than instance eval.

i.e.

```ruby
  before(:init) do |container|
    require "types"
    container.require "my_lib"
  end
```

**Comment by GustavoCaso** [comment]
@solnic @timriley what do you think about the idea of @AMHOL? If we like that approach I can update the code to work that way

**Comment by solnic** [comment]
We already yield the container to the main block. Instance-evaling blocks is mostly to reduce the noise. It also gives us more control over things people can do within these blocks. The only issue I see (from my pov at least), is the bloody `Container.require`.

I'd like to rename it to `require_from_root` because it says what it does, wdyt?

**Comment by timriley** [comment]
@solnic I'd be happy with `require_from_root`. It says what it does and it's sufficiently wordy that no one would use it by accident :)

**Comment by GustavoCaso** [comment]
@solnic @timriley I'm happy with `require_from_root` is pretty specific. PR coming in hot 🌶
