### ISSUE TITLE
Root has to be a pathname not a String as indicated in the example

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-system#7]
I get `dry-component-0.0.1/lib/dry/component/config.rb:9:in `load': undefined method `join' for "app":String (NoMethodError)` when I try the example code:

```ruby
class Application < Dry::Component::Container
  configure do |config|
    config.root = 'app'

    # we set 'lib' relative to `root` as a path which contains class definitions
    # that can be auto-registered
    config.auto_register = 'lib'
  end

  # this alters $LOAD_PATH hence the `!`
  load_paths!('lib')
end
```

I made the `app` string a pathname `config.root = Pathname.new('app')` and it works. Clearly it expect a pathname or assumes it's being instantiated elsewhere. Please let me know if I'm missing something or it's a real bug.

**Comment by solnic** [comment]
Sorry, it's a mistake in the readme but I'd be OK with making it work with strings, too.

**Comment by davidpelaez** [comment]
I'll be nice to have strings. For the sake of exploring and making the best of what you have already released I just sent a small PR for the readme with what I found to be missing in my own experimentation.
