### ISSUE TITLE
Share an example within a gem?

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-system#71]
Hey guys,

I'm having a hard time configuring dry-system within a new gem context. The 2 examples provided in this repo are pretty close but they lack the fact that when creating a new gem, the lib folder look something like this:

```
lib
├── foo
│   └── version.rb
└── foo.rb
```

Where we can then namespace services objects using dry-transactions within a `Transactions` module:

```
lib
├── foo
│   ├── transactions
│   │   └── do_something.rb
│   └── version.rb
└── foo.rb
```

But i'm confused on hot to setup the `configure` hook of dry-system. This is what I have so far:

```ruby
# system/container.rb
module Foo
  class Container < Dry::System::Container
    configure do |config|
      config.root = Pathname(File.dirname(__FILE__)).join('../../')
      config.auto_register = %w(lib/foo/transactions)
    end

    load_paths!('lib/foo')
  end
end
```

but when testing in console with:

```ruby
Foo::Container['transactions.do_something']
NameError: uninitialized constant Transactions::DoSomething
```

It's missing the gem namespace  `Foo`.
Any idea what i'm missing?

Would be nice to include in this repo a full example using a gem as the file structure, what do you think?

**Comment by solnic** [comment]
For support questions please use discourse.dry-rb.org also see https://github.com/dry-rb/dry-system/blob/master/CONTRIBUTING.md
