### ISSUE TITLE
Allow to have optional settings

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-system#73]
The following code seems to not be working as expected:

```ruby
Dry::System.register_component(:foo, provider: :core) do
  settings do
    key :foo, Types::Strict::String
    key :bar, Types::Strict::String.optional
  end
end
```

Then inside a container:

```ruby
boot :foo, from: :core do
  configure do |config|
    config.foo = "..."
  end
end
```

When loading my app, I get:

```
Dry::Struct::Error: [Configuration.new] :bar is missing in Hash input
```

**Comment by GustavoCaso** [comment]
@gottfrois I was able to reproduce the error 😄. I will update you shortly.

**Comment by GustavoCaso** [comment]
Ok. Looks like the settings for bootable components, returns a `Dry::Struct` with the constructor_type of `strict_with_defaults` https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/settings.rb#L35, this type of struct expect the keys to be there but values can be `nil` and you want defaults to be set http://dry-rb.org/gems/dry-struct/

So to make it work with your current setup you could:

```ruby
Dry::System.register_component(:foo, provider: :core) do
  settings do
    key :foo, Types::Strict::String
    key :bar, Types::Strict::String.default('')
  end
end
```

Hope this helps.

**Comment by gottfrois** [comment]
Yep this is what I figured and started to use defaults. But sometimes to use defaults you have to know the internals of the 3rd party tool as `nil` might just no be the proper default.

It would be nice to be able to use `optional` here as well.
Do you think it's doable in a futur release?

**Comment by GustavoCaso** [comment]
It could be something that could be explored maybe we could make the constructor_type `permissive` 

WDYT @solnic?

**Comment by solnic** [comment]
Yes this will be possible once we wrap up dry-types 1.0.0 which will have more flexible hash schemas.

**Comment by timriley** [comment]
This will have been solved in our move to dry-configurable to define the settings for our provider sources in #202.
