### ISSUE TITLE
Can't use auto-registration and stubs in test mode

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-system#74]
I have setup my container to auto register everything under my `lib/foo` folder which, if I understood correctly, is triggered when calling `finalize!` method on the container.

However, calling the `finalize!` method does not allow me to stub anymore.
How do you, auto register classes but also allows for stubs in test mode?

Relevant code:

```ruby
module Foo
  class Container < Dry::System::Container
    configure do |config|
      config.name              = :foo
      config.root              = Pathname(File.dirname(__FILE__)).join('../../')
      config.default_namespace = 'foo'
      config.auto_register     = %w[lib/foo]
    end

    load_paths!('lib')
  end

  Container.finalize!
end
```

In my `spec_helper.rb`:

```ruby
require 'dry/system/stubs'
require 'foo'

RSpec.configure do |config|
  config.before :suite do
    Foo::Container.enable_stubs!
    Foo::Container.stub :repo, Foo::SomeRepo.new
  end
end
```

Outputs:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: Foo::Container.enable_stubs!

RuntimeError:
  can't modify frozen Class
# /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/dry-container-0.6.0/lib/dry/container/stub.rb:44:in `extend_object'
# /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/dry-container-0.6.0/lib/dry/container/stub.rb:44:in `extend'
# /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/dry-container-0.6.0/lib/dry/container/stub.rb:44:in `enable_stubs!'
# /Users/gottfrois/.rvm/gems/ruby-2.4.2/gems/dry-system-0.9.1/lib/dry/system/stubs.rb:27:in `enable_stubs!'
# ./spec/spec_helper.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by solnic** [comment]
Yes, in tests you don't finalize container, so that it's "open" to modifications at run-time. See http://dry-rb.org/gems/dry-system/test-mode/

**Comment by gottfrois** [comment]
Sounds about right, but auto-registration won't work if you don't call `finalize!`. Right now i've managed to get around the issue by conditionally calling `finalize!` depending on the env i'm running the code in.

Would be nice if auto-registration was separated from freezing the container as in test mode, you still want classes to be auto registrating but un-freezed container right?

**Comment by solnic** [comment]
D'ooh. Totally forgot that we now have `stub` as an extension, which disables freezing upon finalization. So, yes, you still want to finalize, it's just that you have to enable stubbing before finalization.

**Comment by solnic** [comment]
Hmm, it's not a good idea to include finalization in the container definition file. It should be external, *something* should finalize it in the right moment. ie in dry-web apps, we finalize the container in `boot.rb` files.

**Comment by GustavoCaso** [comment]
@gottfrois here is an example from one testing app using dry-web-roda https://github.com/GustavoCaso/til_web/blob/master/system/boot.rb

**Comment by gottfrois** [comment]
Interesting, thank you for the feedback guys! I just love your work on the dry gems btw ;)

**Comment by solnic** [comment]
I believe this can be closed.
