### ISSUE TITLE
Gem load is failing with `NoMethodError: undefined method `constructor_type' for Dry::System::Settings::Configuration:Class`

### ISSUE THREAD

**Issue by joycse06** [dry-rb/dry-system#88]
I was reading the doc and wanted to play with this gem from console, installed the gem, then fired up a `pry` console, but the gem load from the console is failing with `NoMethodError: undefined method constructor_type for Dry::System::Settings::Configuration:Class`

Console output:

```
[1] pry(main)> require 'dry-struct'
=> true
[2] pry(main)> Dry::Types
=> Dry::Types
[3] pry(main)> require 'dry-core'
=> true
[4] pry(main)> require 'dry-system'
NoMethodError: undefined method `constructor_type' for Dry::System::Settings::Configuration:Class
Did you mean?  constructor
from /Users/USERNAME/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/dry-system-0.9.2/lib/dry/system/settings.rb:35:in `<class:Configuration>'
[5] pry(main)> require 'rubygems'
=> false
[6] pry(main)> p Gem::Specification.select { |gem| gem.name == 'dry-system' }.map { |gem| [gem.name, gem.version.to_s] }.flatten
["dry-system", "0.9.2"]
=> ["dry-system", "0.9.2"]
```

I definitely have the gem installed, other gems from `dry-rb` are loading properly. I am using this version `2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]` of ruby.

Any pointer on what I can do to debug further will be great.

Thanks in advance.

**Comment by flash-gordon** [comment]
Yeah, that's because latest released of dry-types and dry-struct are not compatible with the current release of dry-system, we're going to fix it very soon, meanwhile you can pin dry-types to '~> 0.12.0' and dry-struct `~> 0.4.0`. Sorry about this!

**Comment by joycse06** [comment]
@flash-gordon Thanks for clarifying that, I switched to using `master` from github instead and it seems to be working now.
