### ISSUE TITLE
Question: Why default to register a instance and not the class?

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-system#9]
I was wondering why you do this. Maybe there's a reason in how Rodakase originally used the container, but I'm not sure. I'm trying to understand the intention a little better to avoid suggesting something against what you wanted to achieve. 

Besides the default instantiation in the `Loader`, I don't know why you used the load path instead of using  full paths on requires to avoid collisions. If I have many containers this is a real risk, but I don't know if you only intended for one component container per app instead of many inside the same body of code. Lotus-container uses a namespace for the container by using a module.

Could you briefly clarify what the intention was? Maybe it's just a small working library you extracted from Rodakase and hadn't considered that, however probably it's the other way around and you wanted it that way for a reason. By knowing this better I can probably contribute or provide better feedback :)

**Comment by solnic** [comment]
The intention was always to use objects, not classes, so we register instances. We could consider making that configurable but you can always just register something manually to override default behavior.

> I don't know why you used the load path instead of using full paths on requires to avoid collisions

I organize my code like libraries, even in app's codebases. So I use namespaces and dir/file structure match namespace. So I would never have a situation where `require "foo"` would load a file that defines `Bar::Foo` class. That's how I avoid collisions.

I suppose requiring files using full paths would not hurt though. It's something to consider.

**Comment by solnic** [comment]
Oh and one more thing - from the very start rodakase (thus dry-component too), has been built with multi app/container setups. There are a couple of improvements to be done though - like making it possible to share deps from one container in with other containers, or automatically prepending root identifier so that you don't have to specify it in import modules and probably few more things :) Regardless, this type of multi app/container setup already works just fine.

**Comment by davidpelaez** [comment]
I split a big app in multiple containers and it ended having a collision risk because I could have `mappers/product` in two separate places taking care of separate data processing steps and concerns and one require could end up in another directory depending on the load path order. 

Maybe I should just nest everything into one directory under the `lib` dir of every container but it's cumbersome when already having multiple dirs per container. But sometimes this feels very big and Java looking, like beyond the point of any use and just impractical. So I think it would be worth having an optional namespace per container. I think it's nice to have a `lib` folder per container and knowing for instance that `lib/aloha.rb` would map to `LibNamespace::Aloha` instead of what it currently expects which is `Aloha` so that I can reuse the name aloha somewhere else. For instance something like `OperationInit` could be duplicated per container, because what "initializing an operation" entitles is different but the name applies any way.

I think I get the point of having instances but from what I have been doing the last weeks it quickly collides with other tools. Consider an Anima object, I need access to the class to pass the hash for initialization so the instance doesn't work very well in some cases. Maybe we could use extra config methods to specify the loading strategy? 

Also, I was unable to find a situation where I would autoregister a lib and not need it available in the load path, so it probably makes sense to link this too better because when you try to autoregister a directory not explicitely in the path it cannot find the file. Maybe the load path method could be lower level?

Finally, I noticed that a container naturally ends up exposing a smaller interface to other container. For instance I created a JSON API with three containers, one for HTTP stuff, one for persistence, and one for data processing and business logic. I ended up exposing a single object from the DB to the business logic and another one from there to the HTTP handler. So in the end it felt like containers could be classes that I could jus instantiate and inject dependencies. This is somewhat different from how I did with dry-component which was registering in the container the dependency on boot, but it felt "too global
". So I don't know if you see a case where the container could be not only a singleton but an instance where initial config like dependencies can be injected? I'm entirely sure about this, just thinking about the possibilities and potential benefits of a more radical boundary given the instantiation vs. the singleton.

Many points in the conversation, just let me know what you think and thanks for the openness and responsiveness. I'm still learning a lot so please feel free if any idea sounds like a plain stupid architectural choice :)

**Comment by solnic** [comment]
> I split a big app in multiple containers and it ended having a collision risk because I could have mappers/product in two separate places taking care of separate data processing steps and concerns and one require could end up in another directory depending on the load path order. 

We can try adding support for including container namespace automatically so that you can have `lib/products/mapper` in two places and `Loader` would assume it's namespaced *if* this behavior is enabled in its container.

> I think I get the point of having instances but from what I have been doing the last weeks it quickly collides with other tools. Consider an Anima object, I need access to the class to pass the hash for initialization so the instance doesn't work very well in some cases.

There are types of objects which should not be registered in container. Anima (thus struct-like data-objects) are one of these types. ie I do not use container for my dry-types, it's not needed.

> Maybe we could use extra config methods to specify the loading strategy?

Yes it could be done but would definitely complicate the library and its usage. I'm not yet sure if I'd support this.

> This is somewhat different from how I did with dry-component which was registering in the container the dependency on boot, but it felt "too global
". So I don't know if you see a case where the container could be not only a singleton but an instance where initial config like dependencies can be injected?

Not sure if I follow. A container which is an instance that gets its deps injected in...injected in by what? :)

**Comment by davidpelaez** [comment]
What types of objects shouldn't be registered? I used it for everything! Basically I used the container as a tool to structure related files covering one big concern that have a single limited way to interact with other concerns. Everything related to persistence goes in the Storage container including helpers, mappers, methods that expose access to specific queries, initialization of the Sequel and plugins/extensions... What shouldn't be registered? Maybe I'm not using it in the most orthodox way.

I agree in keeping simple the config of the library. Maybe solving my question about what shouldn't be registered this will clear out. Also the next point expanding on your final question is also related to this:

Let's say I have an MyApp container which inherits from `Dry::Component::Container`, it has all the business logic and interacts with a `Storage` container that could be replaced for an in memory mock for testing (just for the sake of explaining the point). 

Ideally I'd like to pass the storage in this way: `y = LeStorage.new; x = MyApp.new(storage: y)`, and now I can do `x['ops.create_session].call(input)` and that would run my "operation" that will call methods on `y` that I passed as the `storage:` for _this instance_ of the container. 

Notice I have the resolution access on `x` instead of doing `MyApp['ops.create_session']`. By doing this I know that `CreateSession` will use whatever `storage` was given on initialization, there's no global definition of what `storage` is within `MyApp`. What I'm doing today is `MyApp.register 'storage', LeStorage` but that's what I see as "too" global. I would totally prefer to have a way to "inject" into the container something in one specific point as opposed to registering anywhere on the code.

Maybe I'm overvaluing it, but I think it could be nice to see something like this in my `config.ru`:

```
storage = SQLStorage.new **StorageConfigType[ENV]
handler = BizLogic.new storage: storage
router = HTTPAPI.new operations: handler['operations']

run router['rack']
```

Anywhere else on the code I can test with different storages, handlers or routers to confirm it'll work as expected. It's mostly a benefit of isolation that could be great for testing and avoid entirely the notion of a global resolution within the container. Is it clearer? Makes sense? I suppose this is heavily connected to the "there's no need to register that" point you made before :)

**Comment by sagmor** [comment]
@davidpelaez on #6 I tried to implement the "namespaced" It still needs some work, but I faced similar issues since I wanted to work with a `AppNamespace::SubNamespace::Constant` scheme and having every file looking like `./components/sub_namespace/lib/app_namespace/sub_namespace/constant.rb` felt like a real pain.

**Comment by solnic** [comment]
Gonna close this one as it seems like there's nothing to do here.
