### ISSUE TITLE
Add Container#shutdown

### ISSUE THREAD

**Issue by GustavoCaso** [dry-rb/dry-system#92]
As mentioned in the issue https://github.com/dry-rb/dry-system/issues/90

The lifecycle process is missing the stop method. It has been addressed in the PR https://github.com/dry-rb/dry-system/pull/91

@solnic mentioned also It would be interesting to have a `shutdown` method that goes through all booted components and stop them.

**Comment by davydovanton** [comment]
I think I can help with this feature 🎉

**Comment by timriley** [comment]
@davydovanton I think @GustavoCaso has already done it, in https://github.com/dry-rb/dry-system/pull/91?

**Comment by GustavoCaso** [comment]
@davydovanton so happy you want to work on it. Looking forward to seeing the PR ❤️
